models/node.py
from models import db
from models import ModelMixin
from utils import timestamp

import hashlib


class TopNode(db.Model, ModelMixin):
    __tablename__ = 'top_nodes'
    id = db.Column(db.Integer, primary_key=True)
    created_time = db.Column(db.Integer)
    name = db.Column(db.String(64))
    introduction = db.Column(db.String(128))
    nodes = db.relationship('Node', backref='top_node', lazy='dynamic')
    topics = db.relationship('Topic', backref="top_node", lazy="dynamic")

    def __init__(self, form):
        self.created_time = timestamp()
        self.name = form.get('top_node_name', '')
        self.introduction = form.get('top_node_inctoduction', '')

    def validate(self):
        return True


class Node(db.Model, ModelMixin):
    __tablename__ = 'nodes'
    id = db.Column(db.Integer, primary_key=True)
    created_time = db.Column(db.Integer)
    name = db.Column(db.String(64))
    introduction = db.Column(db.String(128))
    top_node_id = db.Column(db.Integer, db.ForeignKey('top_nodes.id'))
    topics = db.relationship('Topic', backref="node", lazy="dynamic")

    def __init__(self, form):
        self.created_time = timestamp()
        self.top_node_id = int(form.get('top_node', '0'))
        self.name = form.get('node_name', '')
        self.introduction = form.get('node_inctoduction', '')

    def validate(self):
        return True

    def gravatar(self, size=100, default='identicon', rating='g'):
        url = 'http://cn.gravatar.com/avatar'
        hash = hashlib.md5(self.name.encode('utf-8')).hexdigest()
        return '{url}/{hash}?s={size}&d={default}&r={rating}'.format(
            url = url, hash = hash, size = size, default = default, rating = rating)

models/topic.py
from models import db
from models import ModelMixin
from models.node import Node
from utils import timestamp


class Topic(db.Model, ModelMixin):
    __tablename__ = 'topics'
    id = db.Column(db.Integer, primary_key=True)
    created_time = db.Column(db.Integer)
    title = db.Column(db.String(64))
    content = db.Column(db.Text())
    clicked = db.Column(db.Integer)
    visit_count = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref='topic', lazy="dynamic")
    top_node_id = db.Column(db.Integer, db.ForeignKey('top_nodes.id'))
    node_id = db.Column(db.Integer, db.ForeignKey('nodes.id'))

    def __init__(self, form):
        self.created_time = timestamp()
        self.clicked = 0
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.node_id = int(form.get('node', '0'))
        node = Node.query.filter_by(id=self.node_id).first()
        self.top_node_id = node.top_node_id

    def validate(self):
        if len(self.title) > 0:
            return True
        else:
            return False

routes/auth.py
from functools import wraps
from models.role import Permission
from models.user import User
from routes import *
from utils import log


main = Blueprint('auth', __name__)


def permission_required(permission):
    def decorator(f):
        @wraps(f)
        def function(*args, **kwargs):
            if not current_user.can(permission):
                abort(403)
            return f(*args, **kwargs)
        return function
    return decorator


def admin_required(f):
    return permission_required(Permission.ADMINISTER)(f)


@main.route('/')
def index():
    return redirect(url_for('.login_view'))


@main.route('/login')
def login_view():
    flash(u'你要查看的页面需要先登录')
    return render_template('auth/login.html')


@main.route('/register')
def register_view():
    return render_template('auth/register.html')


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    u = User.validate(form)
    if u is not None:
        login_user(u)
        log('登录成功')
        return redirect(url_for('topic.index'))
    else:
        log('登录失败')
        flash(u'用户名或密码错误')
    return redirect(url_for('auth.login_view'))


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    u = User(form)
    user = User.query.filter_by(username=u.username).first()
    if user is None and u.validate_register():
        log('注册成功')
        u.save()
        return redirect(url_for('auth.login_view'))
    else:
        log('注册失败')
        if user is not None:
            flash(u'注册失败，用户名已注册')
        else:
            flash(u'注册失败，用户名或密码不能为空')
    return redirect(url_for('auth.register_view'))


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login_view'))

routes/topic.py
from models.topic import Topic
from models.comment import Comment
from models.user import User
from models.node import TopNode
from models.node import Node
from routes import *
from routes.auth import login_required
from routes.auth import current_user
from utils import log
import time


main = Blueprint('topic', __name__)

Model = Topic


@main.route('/')
def index():
    top_node = TopNode.query.first()
    if top_node is not None:
        id = top_node.id
        return redirect(url_for('topic.tab', id=id))
    return redirect(url_for('topic.all'))


@main.route('/tab/<int:id>')
def tab(id):
    all_list = {
        'top_node_list': TopNode.query.all(),
    }
    statistics = {
        'user': User.query.count(),
        'topic': Topic.query.count(),
        'comment': Comment.query.count()
    }
    top_node = TopNode.query.filter_by(id=id).first()
    if top_node is not None:
        all_list['topic_list'] = Topic.query.filter_by(top_node_id=top_node.id).order_by(Topic.created_time.desc()).all()
        all_list['node_list'] = top_node.nodes
    else:
        all_list['topic_list'] = []
        all_list['node_list'] = []
    return render_template('topic_index.html', top_node_id=id, all_list=all_list, statistics=statistics)


@main.route('/topic/all')
def all():
    all_list = {
        'top_node_list': TopNode.query.all(),
        'node_list': Node.query.all(),
        'topic_list': Topic.query.order_by(Topic.created_time.desc()).all()
    }
    statistics = {
        'user': User.query.count(),
        'topic': Topic.query.count(),
        'comment': Comment.query.count()
    }
    return render_template('topic_all.html', all_list=all_list, statistics=statistics)


@main.route('/t/<int:id>')
def topic(id):
    topic = Model.query.get(id)
    if topic is not None:
        topic.clicked += 1
        topic.save()
        return render_template('topic.html', topic=topic)
    return redirect(url_for('topic.index'))


@main.route('/add')
def add_view():
    node_list = Node.query.all()
    return render_template('topic_add.html', node_list=node_list)


@main.route('/add', methods=['POST'])
@login_required
def add():
    form = request.form
    t = Topic(form)
    if t.validate():
        t.user = current_user._get_current_object()
        t.save()
        flash(u'发布成功')
        return redirect(url_for('topic.topic', id=t.id))
    else:
        flash(u'标题不能为空')
    return redirect(url_for('topic.add_view'))


@main.route('/add/from/node', methods=['POST'])
@login_required
def add_from_node():
    form = request.form
    t = Topic(form)
    if t.validate():
        t.user = current_user._get_current_object()
        t.save()
        flash(u'创建新主题成功')
        return redirect(url_for('topic.node', id=t.node.id))
    return redirect(url_for('topic.index'))


@main.route('/edit/<int:id>')
@login_required
def edit_view(id):
    topic = Model.query.get(id)
    if topic is not None and (current_user == topic.user or current_user.is_administrator()):
        node_list = Node.query.all()
        return render_template('topic_edit.html', topic=topic, node_list=node_list)
    return redirect(url_for('topic.topic', id=id))


@main.route('/edit/<int:id>', methods=['POST'])
@login_required
def edit(id):
    form = request.form
    t = Topic(form)
    topic = Model.query.get(id)
    if topic is not None and t.validate() and (current_user == topic.user or current_user.is_administrator()):
        topic.title = t.title
        topic.content = t.content
        topic.node_id = t.node_id
        topic.save()
        flash(u'更改成功')
        return redirect(url_for('topic.topic', id=id))
    else:
        flash(u'标题不能为空')
    return redirect(url_for('topic.edit_view', id=id))


@main.route('/delete/<int:id>')
@login_required
def delete(id):
    topic = Model.query.get(id)
    if topic is not None and (current_user == topic.user or current_user.is_administrator()):
        for c in topic.comments:
            c.delete()
        topic.delete()
        return redirect(url_for('topic.index'))
    return redirect(url_for('topic.topic', id=id))


@main.route('/comment', methods=['POST'])
@login_required
def comment():
    form = request.form
    c = Comment(form)
    log('topic id', c.topic_id)
    log('comment', c.content)
    if c.validate():
        user = current_user._get_current_object()
        timestamp = int(time.time())
        last_comment = Comment.query.filter_by(user_id=user.id).order_by(Comment.created_time.desc()).first()
        if last_comment is None:
            c.user = user
            c.save()
        elif timestamp - last_comment.created_time > 2:
            c.user = user
            c.save()
        else:
            flash(u'2 秒之内只能回复一次')
    else:
        flash(u'回复内容不能为空')

    return redirect(url_for('topic.topic', id=c.topic_id))


@main.route('/comment/delete/<int:id>')
@login_required
def comment_delete(id):
    c = Comment.query.get(id)
    if c is not None and (current_user == c.user or current_user.is_administrator()):
        c.delete()
    return redirect(url_for('topic.topic', id=c.topic_id))


@main.route('/node/<int:id>')
def node(id):
    n = Node.query.get(id)
    if n is not None:
        topic_list = Topic.query.filter_by(node_id=n.id).order_by(Topic.created_time.desc()).all()
        return render_template('node.html', n=n, topic_list=topic_list)
    return redirect(url_for('topic.index'))

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% block head%}
        <title>V2EX{% block title%}{% endblock %}</title>
        {% block style %}
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/v2ex.css') }}" type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/ya.css') }}" type="text/css">
        {% endblock %}
        {% block script %}
        <script src="http://cdn.bootcss.com/jquery/3.1.0/jquery.js"></script>
        <script src="http://cdn.bootcss.com/showdown/1.4.3/showdown.min.js"></script>
        {% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block navbar %}
        <div class="ya-navbar">
            <div class="ya-container ya-relative">
                <a href="{{ url_for("topic.index") }}"><img class="ya-navbar-logo" src="{{ url_for('static', filename='img/v2ex_logo.png') }}"></a>
                <img class="ya-navbar-search" src="{{ url_for('static', filename='img/v2ex_search.png') }}">
                <input class="ya-navbar-search-input" placeholder="施工中">
                <div class="ya-navbar-items">
                    {% if current_user.is_authenticated %}
                    <a class="ya-navbar-item ya-float-right" href="{{ url_for("auth.logout") }}">登出</a>
                    <a class="ya-navbar-item ya-float-right" href="{{ url_for("user.settings") }}">设置</a>
                    {% if current_user.is_administrator() %}
                    <a class="ya-navbar-item ya-float-right" href="{{ url_for("manage.index") }}">管理</a>
                    {% endif %}
                    {% else %}
                    <a class="ya-navbar-item ya-float-right" href="{{ url_for("auth.login_view") }}">登录</a>
                    <a class="ya-navbar-item ya-float-right" href="{{ url_for("auth.register_view") }}">注册</a>
                    {% endif %}
                    <a class="ya-navbar-item ya-float-right" href="{{ url_for("topic.index") }}">首页</a>
                </div>
            </div>
        </div>
        {% endblock %}
        {% block content %}
        <div class="v2ex-wrapper">
            <div class="ya-container">
                <div class="v2ex-sidebar-container ya-float-right">
                    {% block sidebar %}
                    {% endblock %}
                </div>
                <div class="v2ex-main-container">
                    {% block main %}
                    {% endblock %}
                </div>
            </div>
        </div>
        {% endblock %}
        {% block footer %}
        <div class="v2ex-footer">
            <div class="v2ex-footer-nav">
                <a class="v2ex-label-default" href="#">关于</a>
            </div>
            <p class="v2ex-text-default">创意工作者们的社区</p>
            <p class="v2ex-text-default">World is powered by xiaocaigua</p>
        </div>
        {% endblock %}
    </body>
</html>

templates/node.html
{% extends "base.html" %}

{% block sidebar %}
{% if current_user.is_anonymous %}
{% include 'auth/_anomyous.html' %}
{% else %}
{% include 'auth/_user.html' %}
{% endif %}
{% endblock %}

{% block main %}
<div class="v2ex-box v2ex-content">
    <div class="v2ex-nav-h1 ya-overflow">
        <img class="v2ex-node-avatar ya-float-left" src="{{ n.gravatar() }}">
        <a href="{{ url_for('topic.index') }}">V2EX</a>
        <span>&nbsp;>&nbsp;</span>
        <a href="{{ url_for('topic.node', id=n.id) }}">{{ n.name }}</a>
        <a class="v2ex-text-gray2 v2ex-padding ya-float-right" href="#">加入收藏</a>
        <span class="v2ex-text-gray2 v2ex-padding-right ya-float-right">{{ n.topics.count() }}</span>
        <p class="v2ex-p-gray">
            {% if n.introduction %}
            {{ n.introduction }}
            {% else %}
            暂无简介
            {% endif %}
        </p>
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('topic.add_view') }}"><button class="v2ex-button-primary">创建新主题</button></a>
        {% endif %}
    </div>
    <div class="v2ex-main-cell">
        {% for message in get_flashed_messages() %}
        <p class="v2ex-message" onclick="$(this).slideUp('fast');">
            {{ message }}
        </p>
        {% endfor %}
    </div>
    <div class="v2ex-main-cell">
        {% for t in topic_list %}
        <div class="v2ex-topic-container">
            <img class="v2ex-user-avatar" src="{{ t.user.gravatar() }}"></img>
            <span class="v2ex-comments-count">{{ t.comments.count() }}</span>
            <p class="v2ex-topics-title"><a class="v2ex-a-default" href="{{ url_for("topic.topic", id=t.id) }}">{{ t.title }}</a></p>
            <div class="v2ex-topics-footer">
                <a class="v2ex-span-gray-default" href="{{ url_for('topic.node', id=t.node.id) }}">{{ t.node.name }}</a>
                <span class="v2ex-span-gray-default">•</span>
                <a class="v2ex-a-gray-default" href="#">{{ t.user.username }}</a>
                <span class="v2ex-span-gray-default">•&nbsp{{ t.get_created_time() }}</span>
                {% if t.comments.count() != 0 %}
                <span class="v2ex-span-gray-default">•&nbsp最后回复来自 </span>
                <a class="v2ex-a-gray-default" href="#">{{ t.comments[-1].user.username }}</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% if current_user.is_authenticated %}
<div class="v2ex-box v2ex-content">
    <div class="v2ex-main-cell v2ex-padding-left v2ex-comment-div">
        <form action="{{ url_for('topic.add_from_node') }}" method="post">
            <input class="ya-hide" name="node" value="{{ n.id }}">
            <input class="v2ex-node-add-title" type="text" name="title" value="" placeholder="请输入主题标题，如果标题能够表达完整内容，则正文可以为空">
            <textarea class="v2ex-node-add-content" name="content" placeholder="正文"></textarea>
            <button class="v2ex-button-primary" type="submit" name="button">创建新主题</button>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

templates/topic.html
{% extends "base.html" %}

{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='js/topic.js') }}"></script>
{% endblock %}

{% block sidebar %}
{% if current_user.is_anonymous %}
{% include 'auth/_anomyous.html' %}
{% else %}
{% include 'auth/_user.html' %}
{% endif %}
{% endblock %}

{% block main %}
<div class="v2ex-box v2ex-content">
    <div class="v2ex-nav-h1 ya-overflow">
        <img class="v2ex-topic-avatar ya-float-right" src="{{ topic.user.gravatar() }}">
        <a href="{{ url_for("topic.index") }}">V2EX</a>
        <span>&nbsp;>&nbsp;</span>
        <a href="{{ url_for('topic.node', id=topic.node.id) }}">{{ topic.node.name }}</a>
        <p class="v2ex-topic-title">{{ topic.title }}</p>
        <div>
            <a class="v2ex-a-gray-default" href="#">{{ topic.user.username }}</a>
            <span class="v2ex-span-gray-default">•&nbsp{{ topic.get_created_time() }}</span>
            {% if current_user == topic.user or current_user.is_administrator() %}
            •&nbsp<a class="v2ex-a-gray-default" href="{{ url_for('topic.edit_view', id=topic.id) }}">编辑</a>
            •&nbsp<a class="v2ex-a-gray-default" href="{{ url_for('topic.delete', id=topic.id) }}">删除</a>
            {% endif %}
        </div>
    </div>
    <div class="v2ex-main-cell">
        {% for message in get_flashed_messages() %}
        <p class="v2ex-message" onclick="$(this).slideUp('fast');">
            {{ message }}
        </p>
        {% endfor %}
    </div>
    <p id="content" class="ya-hide">{{ topic.content }}</p>
    <div id="content-show" class="v2ex-main-cell v2ex-topic-content v2ex-markdown-preview"></div>
    <div class="v2ex-main-cell ya-overflow v2ex-topic-footer">
        <a class="v2ex-label-other" href="#">加入收藏</a>
        <a class="v2ex-label-other" href="#">Tweet</a>
        <span class="v2ex-span-gray-default ya-float-right">•&nbsp1 人收藏</span>
        <span class="v2ex-span-gray-default ya-float-right">{{ topic.clicked }} 次点击&nbsp</span>
    </div>
</div>
<div id="comments" class="v2ex-box v2ex-content">
    <div class="v2ex-comments-header">
        <span class="v2ex-span-gray-default">{{ topic.comments.count() }} 回复</span>
    </div>
    {% for c in topic.comments %}
    <div class="v2ex-topic-container v2ex-main-cell">
        <img class="v2ex-user-avatar" src="{{ c.user.gravatar() }}"></img>
        <div class="v2ex-comment-footer">
            <a class="v2ex-a-gray-default" href="#">{{ c.user.username }}</a>
            <span class="v2ex-span-gray-default">&nbsp{{ c.get_created_time() }}</span>
            {% if current_user == c.user or current_user.is_administrator() %}
            <a class="v2ex-a-gray-default" href="{{ url_for('topic.comment_delete', id=c.id) }}">删除</a>
            {% endif %}
        </div>
        <p class="v2ex-comment-content"><a class="v2ex-a-default" href="{{ url_for('topic.topic', id=topic.id) }}">{{ c.content }}</a></p>
    </div>
    {% endfor %}
</div>
{% if current_user.is_authenticated %}
<div class="v2ex-box v2ex-content">
    <div class="v2ex-main-cell v2ex-padding-left">
        <p class="v2ex-p-black">添加一条新回复</p>
    </div>
    <div class="v2ex-main-cell v2ex-padding-left v2ex-comment-div">
        <form action="{{ url_for('topic.comment') }}" method="post">
            <input type="text" name="topic_id" class="ya-hide" value="{{ topic.id }}">
            <textarea class="v2ex-comment-input" name="comment"></textarea>
            <button class="v2ex-button-primary" type="submit" name="button">回复</button>
            <span class="v2ex-span-gray-default ya-float-right">请尽量让自己的回复能够对别人有所帮助</span>
        </form>
    </div>
    <div class="v2ex-main-cell">
        <a class="v2ex-a-gray1 v2ex-padding ya-float-right" href="{{ url_for('topic.index') }}">←V2EX</a>
    </div>
</div>
{% endif %}
{% endblock %}

templates/topic_add.html
{% extends "base.html" %}

{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='js/topic_add.js') }}"></script>
{% endblock %}

{% block sidebar %}
<div class="v2ex-box v2ex-sidebar ya-overflow">
    <div class="v2ex-sidebar-cell">
        <p class="v2ex-sidebar-title2">发帖提示</p>
        <ul>
            <li>
                <p class="v2ex-p-black">主题标题</p>
                <span>请在标题中描述内容要点。如果一件事情在标题的长度内就已经可以说清楚，那就没有必要写正文了。</span>
            </li>
            <li>
                <p class="v2ex-p-black">正文</p>
                <span>可以在正文中为你要发布的主题添加更多细节。V2EX 支持 GitHub Flavored Markdown 文本标记语法。</br></br>在正式提交之前，你可以点击本页面左下角的“预览主题”来查看 Markdown 正文的实际渲染效果。</span>
            </li>
            <li>
                <p class="v2ex-p-black">选择节点</p>
                <span>在最后，请为你的主题选择一个节点。恰当的归类会让你发布的信息更加有用。</br></br>你可以在主题发布后 300 秒内，对标题或者正文进行编辑。同时，在 300 秒内，你可以重新为主题选择节点</span>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

{% block main %}
<div class="v2ex-box">
    <div class="v2ex-nav-h1">
        <a href="{{ url_for('topic.index') }}">V2EX</a>
        <span>&nbsp;>&nbsp;</span>
        <span>创作新主题</span>
    </div>
    <div class="v2ex-main-cell">
        {% for message in get_flashed_messages() %}
        <p class="v2ex-message" onclick="$(this).slideUp('fast');">
            {{ message }}
        </p>
        {% endfor %}
    </div>
    <form action="{{ url_for('topic.add') }}" method="post">
        <div class="v2ex-main-cell v2ex-padding-left">
            <p class="v2ex-p-black">主题标题</p>
        </div>
        <div class="v2ex-main-cell v2ex-padding-left">
            <input class="v2ex-add-title" type="text" name="title" value="" placeholder="请输入主题标题，如果标题能够表达完整内容，则正文可以为空">
        </div>
        <div class="v2ex-main-cell v2ex-padding-left">
            <p class="v2ex-p-black">正文</p>
        </div>
        <div class="v2ex-main-cell v2ex-padding-left">
            <textarea id="content" class="v2ex-add-content" name="content" onkeyup="markdown_convert()"></textarea>
        </div>
        <div class="v2ex-main-cell v2ex-padding-left">
            <select class="v2ex-add-node" name="node">
                {% for n in node_list %}
                    <option value="{{ n.id }}">{{ n.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="v2ex-main-cell v2ex-padding-left v2ex-nav-default">
            <sapn>最热节点</span>
            {% for n in node_list %}
            <a class="v2ex-label-other" href="#">{{ n.name }}</a>
            {% endfor %}
        </div>
        <div class="v2ex-main-cell v2ex-padding-left v2ex-add-button-group">
            <button class="v2ex-button-primary" type="button" name="button" onclick="markdown_preview()">预览主题</button>
            <button class="v2ex-button-primary ya-float-right" type="submit" name="button">发布主题</button>
        </div>
    </form>
    <div id="markdown-preview" class="v2ex-main-cell v2ex-padding-left v2ex-markdown-preview ya-hide"></div>
</div>
{% endblock %}

templates/topic_edit.html
{% extends "base.html" %}

{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='js/topic_add.js') }}"></script>
{% endblock %}

{% block sidebar %}
<div class="v2ex-box v2ex-sidebar ya-overflow">
    <div class="v2ex-sidebar-cell">
        <p class="v2ex-sidebar-title2">发帖提示</p>
        <ul>
            <li>
                <p class="v2ex-p-black">主题标题</p>
                <span>请在标题中描述内容要点。如果一件事情在标题的长度内就已经可以说清楚，那就没有必要写正文了。</span>
            </li>
            <li>
                <p class="v2ex-p-black">正文</p>
                <span>可以在正文中为你要发布的主题添加更多细节。V2EX 支持 GitHub Flavored Markdown 文本标记语法。</br></br>在正式提交之前，你可以点击本页面左下角的“预览主题”来查看 Markdown 正文的实际渲染效果。</span>
            </li>
            <li>
                <p class="v2ex-p-black">选择节点</p>
                <span>在最后，请为你的主题选择一个节点。恰当的归类会让你发布的信息更加有用。</br></br>你可以在主题发布后 300 秒内，对标题或者正文进行编辑。同时，在 300 秒内，你可以重新为主题选择节点</span>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

{% block main %}
<div class="v2ex-box">
    <div class="v2ex-nav-h1">
        <a href="{{ url_for("topic.index") }}">V2EX</a>
        <span>&nbsp;>&nbsp;</span>
        <span>编辑主题</span>
    </div>
    <div class="v2ex-main-cell">
        {% for message in get_flashed_messages() %}
        <p class="v2ex-message" onclick="$(this).slideUp('fast');">
            {{ message }}
        </p>
        {% endfor %}
    </div>
    <form action="{{ url_for('topic.edit', id=topic.id) }}" method="post">
        <div class="v2ex-main-cell v2ex-padding-left">
            <p class="v2ex-p-black">主题标题</p>
        </div>
        <div class="v2ex-main-cell v2ex-padding-left">
            <input class="v2ex-add-title" type="text" name="title" value="{{ topic.title }}" placeholder="请输入主题标题，如果标题能够表达完整内容，则正文可以为空">
        </div>
        <div class="v2ex-main-cell v2ex-padding-left">
            <p class="v2ex-p-black">正文</p>
        </div>
        <div class="v2ex-main-cell v2ex-padding-left">
            <textarea id="content" class="v2ex-add-content" name="content" onkeyup="markdown_convert()">{{ topic.content }}</textarea>
        </div>
        <div class="v2ex-main-cell v2ex-padding-left">
            <select class="v2ex-add-node" name="node">
                {% for n in node_list %}
                    <option value="{{ n.id }}">{{ n.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="v2ex-main-cell v2ex-padding-left v2ex-nav-default">
            <sapn>最热节点</span>
            {% for n in node_list %}
            <a class="v2ex-label-other" href="#">{{ n.name }}</a>
            {% endfor %}
        </div>
        <div class="v2ex-main-cell v2ex-padding-left v2ex-add-button-group">
            <button class="v2ex-button-primary" type="button" name="button" onclick="markdown_preview()">预览主题</button>
            <button class="v2ex-button-primary ya-float-right" type="submit" name="button">发布主题</button>
        </div>
    </form>
    <div id="markdown-preview" class="v2ex-main-cell v2ex-padding-left v2ex-markdown-preview ya-hide"></div>
</div>
{% endblock %}