models/user.py
import hashlib
from flask import current_app
from flask_login import LoginManager
from flask_login import UserMixin
from flask_login import AnonymousUserMixin
from werkzeug.security import generate_password_hash
from werkzeug.security import check_password_hash
from models import db
from models import ModelMixin
from models.role import Role
from models.role import Permission
from utils import timestamp


class User(db.Model, ModelMixin, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    created_time = db.Column(db.Integer)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    introduction = db.Column(db.String(128))
    avatar = db.Column(db.String(128))
    topics = db.relationship('Topic', backref='user')
    comments = db.relationship('Comment', backref='user')
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    @property
    def password(self):
        raise AttributeError(u'密码不可读')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    @classmethod
    def validate(cls, form):
        username = form.get('username', '')
        password = form.get('password', '')
        user = User.query.filter_by(username=username).first()
        if user is not None and check_password_hash(user.password_hash, password):
            return user
        else:
            return None

    def validate_register(self):
        if len(self.username) > 0:
            return True
        else:
            return False

    def change_password(self, form):
        password = form.get('password', '')
        password_new = form.get('password_new', '')
        password_new_repeat = form.get('password_new_repeat', '')
        r = {
            'setting_ok': False,
        }
        if check_password_hash(self.password_hash, password):
            if password_new == password_new_repeat:
                self.password = password_new
                self.save()
                r['setting_ok'] = True
            else:
                r['error_message'] = u'新密码两次输入不一致'
        else:
            r['error_message'] = u'当前密码错误'
        return r

    def gravatar(self, size=100, default='identicon', rating='g'):
        if self.avatar is not None:
            return self.avatar
        else:
            url = 'http://cn.gravatar.com/avatar'
            hash = hashlib.md5(self.username.encode('utf-8')).hexdigest()
            s = '{url}/{hash}?s={size}&d={default}&r={rating}'.format(
                url=url,
                hash=hash,
                size=size,
                default=default,
                rating=rating
            )
            return s

    def can(self, permissions):
        return self.role is not None and \
            (self.role.permissions & permissions) == permissions

    def is_administrator(self):
        return self.can(Permission.ADMINISTER)

    def __init__(self, form):
        self.created_time = timestamp()
        self.username = form.get('username', '')
        self.password = form.get('password', '')
        role = None
        if self.username == current_app.config['ADMIN']:
            role = Role.query.filter_by(name='Administrator').first()
            print('admin role', role)
        else:
            role = Role.query.filter_by(name='User').first()
            print('role', role)
        self.role_id = role.id


class AnonymousUser(AnonymousUserMixin):
    def can(slef, permissions):
        return False

    def is_administrator(self):
        return False


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login_view'
login_manager.anonymous_user = AnonymousUser


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

routes/user.py
import os
from werkzeug import secure_filename
from flask import current_app
from routes import *
from routes.auth import login_required
from routes.auth import current_user
from utils import log


main = Blueprint('user', __name__)


def allowed_file(filename):
    allowed_extensions = {'png', 'jpg', 'jpeg', 'gif'}
    allow = '.' in filename and filename.rsplit('.', 1)[1] in allowed_extensions
    return allow


@main.route('/')
@login_required
def index():
    return redirect(url_for('user.settings'))


@main.route('/settings')
@login_required
def settings():
    user = current_user._get_current_object()
    return render_template('user/setting.html', user=user)


@main.route('/settings/avatar')
@login_required
def settings_avatar():
    user = current_user._get_current_object()
    return render_template('user/avatar_upload.html', user=user)


@main.route('/avatar_upload', methods=['POST'])
@login_required
def avatar_upload():
    file = request.files['file']
    if file and allowed_file(file.filename):
        user = current_user._get_current_object()
        extension = secure_filename(file.filename).split('.')[-1]
        filename = '{}_avatar.{}'.format(user.username, extension)
        log('filename', filename)
        file.save(os.path.join(current_app.config['AVATAR_FOLDER'], filename))
        user.avatar = url_for('user.avatar', avatar_name=filename)
        # log('user.avatar,', user.avatar)
        user.save()
        flash(u'头像上传成功')
    return redirect(url_for('user.settings_avatar'))


@main.route('/avatar/<avatar_name>')
def avatar(avatar_name):
    return send_from_directory(current_app.config['AVATAR_FOLDER'], avatar_name)


@main.route('/change_password', methods=['POST'])
@login_required
def change_password():
    form = request.form
    user = current_user._get_current_object()
    r = user.change_password(form)
    if r['setting_ok']:
        flash(u'密码更改成功')
        return redirect(url_for('auth.logout'))
    flash(r['error_message'])
    return redirect(url_for('user.index'))

templates/user/avatar_upload.html
{% extends "base.html" %}

{% block sidebar %}
{% include 'auth/_user.html' %}
{% endblock %}

{% block main %}
<div class="v2ex-box v2ex-content">
    <div class="v2ex-nav-h1">
        <a href="{{ url_for('topic.index') }}">V2EX</a>
        <span>&nbsp;>&nbsp;</span>
        <a href="{{ url_for('user.settings')}}">设置</a>
        <span>&nbsp;>&nbsp;</span>
        <span>头像上传</span>
    </div>
    <div class="v2ex-main-cell">
        {% for message in get_flashed_messages() %}
        <p class="v2ex-message" onclick="$(this).slideUp('fast');">
            {{ message }}
        </p>
        {% endfor %}
    </div>
    <div class="v2ex-main-cell">
        <div class="v2ex-input-container">
            <form action="{{ url_for('user.avatar_upload') }}" method="post" enctype="multipart/form-data">
                <table>
                    <tr>
                        <td align="right"><span class="v2ex-text-gray2 v2ex-input-tip">当前头像</span></td>
                        <td align="left">
                            <img class="v2ex-user-avatar_l" src="{{ user.gravatar() }}" />
                            <img class="v2ex-user-avatar_m" src="{{ user.gravatar() }}" />
                            <img class="v2ex-user-avatar_s" src="{{ user.gravatar() }}" />
                        </td>
                    </tr>
                    <tr>
                        <td align="right"><span class="v2ex-text-gray2 v2ex-input-tip">选择一个图片文件</span></td>
                        <td><input type=file name=file></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><span class="v2ex-text-gray2 v2ex-input-tip">支持 2MB 以内的 PNG / JPG / GIF 文件</span></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><button class="v2ex-button-primary" type="submit" name="button">开始上传</button>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/user/setting.html
{% extends "base.html" %}

{% block sidebar %}
{% include 'auth/_user.html' %}
{% endblock %}

{% block main %}
<div class="v2ex-box v2ex-content">
    <div class="v2ex-nav-h1">
        <a href="{{ url_for("topic.index") }}">V2EX</a>
        <span>&nbsp;>&nbsp;</span>
        <span>设置</span>
    </div>
    <div class="v2ex-main-cell">
        <div class="v2ex-input-container">
            <form action="" method="post">
                <table>
                    <tr>
                        <td align="right"><span class="v2ex-text-gray2 v2ex-input-tip">用户名</span></td>
                        <td align="left"><span class="v2ex-span-gray-default">{{ user.username }}</span></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <button class="v2ex-button-primary" type="button" name="button">保存设置</button>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>

<div class="v2ex-box v2ex-content">
    <div class="v2ex-main-cell v2ex-padding-left v2ex-padding-right">
        <p class="v2ex-p-black">头像上传</p>
    </div>
    <div class="v2ex-main-cell">
        <div class="v2ex-input-container">
            <table>
                <tr>
                    <td align="right"><span class="v2ex-text-gray2 v2ex-input-tip">当前头像</span></td>
                    <td align="left">
                        <img class="v2ex-user-avatar_l" src="{{ user.gravatar() }}" />
                        <img class="v2ex-user-avatar_m" src="{{ user.gravatar() }}" />
                        <img class="v2ex-user-avatar_s" src="{{ user.gravatar() }}" />
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <a href="{{ url_for('user.settings_avatar') }}"><button class="v2ex-button-primary" type="button" name="button">上传新头像</button></a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="v2ex-main-cell v2ex-padding-left">
        <p class="v2ex-p-black">关于头像的规则</p>
        <ul>
            <li>
                <span>V2EX 禁止使用任何低俗或者敏感图片作为头像</span>
            </li>
            <li>
                <span>如果你是男的，请不要用女人的照片作为头像，这样可能会对其他会员产生误导</span>
            </li>
        </ul>
    </div>
</div>

<div class="v2ex-box v2ex-content">
    <div class="v2ex-main-cell v2ex-padding-left">
        <p class="v2ex-p-black">更改密码</p>
    </div>
    <div class="v2ex-main-cell">
        {% for message in get_flashed_messages() %}
        <p class="v2ex-message" onclick="$(this).slideUp('fast');">
            {{ message }}
        </p>
        {% endfor %}
    </div>
    <div class="v2ex-main-cell">
        <div class="v2ex-input-container">
            <form action="{{ url_for('user.change_password') }}" method="post">
                <table>
                    <tr>
                        <td align="right"><span class="v2ex-text-gray2 v2ex-input-tip">当前密码</span></td>
                        <td align="left"><input class="v2ex-input" type="password" name="password" value=""></td>
                    </tr>
                    <tr>
                        <td align="right"><span class="v2ex-text-gray2 v2ex-input-tip">新密码</span></td>
                        <td align="left"><input class="v2ex-input" type="password" name="password_new" value=""></td>
                    </tr>
                    <tr>
                        <td align="right"><span class="v2ex-text-gray2 v2ex-input-tip">再次输入新密码</span></td>
                        <td align="left"><input class="v2ex-input" type="password" name="password_new_repeat" value=""></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <button class="v2ex-button-primary" type="submit" name="button">更改密码</button>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>
{% endblock %}